title: Andy (Zi'an) Wang
# logo: /assets/img/headshot_circle.png
# description: text below image
# show_downloads: true
theme: jekyll-theme-minimal
collections:
  blogs:
    output: true
    permalink: /blogs/:path/
